name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Vite 7 requires Node 20.19+ or 22.12+; use the latest 22.x
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # ----- Build the site -----
      - name: Build Vite app
        run: npm run build

      # ----- Deploy to GitHub Pages using official actions -----
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
