name: Nightly JSON Update

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run geojson data download script
        run: node scripts/download-geojson.cjs

      - name: Run location data download script
        run: node scripts/download-locations.cjs

      - name: Run drop-in data download script
        run: node scripts/download-drop-in.cjs

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add "public/Parks and Recreation Facilities - 4326.geojson" "public/Locations.json" "public/Drop-in.json"
          git commit -m "Nightly update of drop-in recreation JSON files" || echo "No changes to commit"
          git push

      - name: Build Vite app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
