name: Nightly JSON Update (Pages)

on:
  schedule:
    - cron: '0 7 * * *' # 07:00 UTC nightly
  workflow_dispatch:

# Needed to push commits to main (contents) and to deploy Pages (pages + id-token)
permissions:
  contents: write
  pages: write
  id-token: write

# Prevent overlapping Pages deploys
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Vite 7 requires Node 20.19+ or 22.12+; use the latest 22.x
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # ----- Generate your data files -----
      - name: Run geojson data download script
        run: node scripts/download-geojson.cjs

      - name: Run location data download script
        run: node scripts/download-locations.cjs

      - name: Run drop-in data download script
        run: node scripts/download-drop-in.cjs

      # ----- Commit JSON changes back to main (if any) -----
      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "public/Parks and Recreation Facilities - 4326.geojson" "public/Locations.json" "public/Drop-in.json"

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Nightly update of drop-in recreation JSON files"
            git push
          fi

      # ----- Build the site -----
      - name: Build Vite app
        run: npm run build

      # ----- Deploy to GitHub Pages using official actions -----
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
